discoverer: Gst.init needs an argument
Fixed: `TypeError: init() missing 1 required positional argument: 'argv'`

The argument is mandatory if [gi/overrides/Gst.py](https://gitlab.freedesktop.org/gstreamer/gst-python/-/blob/1.18.5/gi/overrides/Gst.py#L727) is installed.